# SkillGen remote run on Kaggle (T4). Generated by scripts/kaggle_push.py; do not edit by hand.
# Clones the repo at a fixed git ref, installs the [train] extra, trains one config and copies
# the experiment folder (adapter, run_meta.json, length reports) to /kaggle/working (= outputs).
import os
import shutil
import subprocess
import sys

REPO = "https://github.com/SRogDev/skillgen.git"
REF = "__REF__"
CONFIG = "__CONFIG__"


def sh(cmd: str) -> None:
    print("$", cmd, flush=True)
    subprocess.run(cmd, shell=True, check=True)


sh(f"git clone -q {REPO} /kaggle/temp/skillgen && cd /kaggle/temp/skillgen && git checkout -q {REF} && git log --oneline -1")
os.chdir("/kaggle/temp/skillgen")
sh("nvidia-smi --query-gpu=name,memory.total --format=csv")
sh("pip install -q uv && uv pip install --system -q -e '.[train]'")
sh("pip list 2>/dev/null | grep -iE '^(torch|unsloth|trl|transformers|peft|bitsandbytes) '")

try:  # optional W&B: add WANDB_API_KEY in the notebook's Add-ons -> Secrets
    from kaggle_secrets import UserSecretsClient
    os.environ["WANDB_API_KEY"] = UserSecretsClient().get_secret("WANDB_API_KEY")
    print("W&B key found")
except Exception:
    os.environ["WANDB_MODE"] = "disabled"

sys.path.insert(0, "src")
status = 0
try:
    from skillgen.train import train
    print("adapter saved to", train(CONFIG))
except Exception:
    import traceback
    traceback.print_exc()
    status = 1
finally:
    if os.path.isdir("experiments"):
        shutil.copytree("experiments", "/kaggle/working/experiments", dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns("checkpoints"))
sys.exit(status)
